     
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/react-app 
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_react_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/configure_nginx.sh
      timeout: 300
      runas: root
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
